name: specembedding
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - rdkit
  - tqdm
  - matplotlib
  - scipy
  - scikit-learn
  - huggingface_hub
  - pip
  - pip:
    - torch-geometric
    - matchms
    - myopic_mces
