general:
  seed: 42
  device: "cuda" # or "cpu"
  save_dir: "./checkpoints"

data:
  dataset_type: "massspecgym" # or "local"
  data_path: data
  cache_path: "data/train_cache"
  tokenizer:
    max_len: 100
    show_progress_bar: true

augmentation:
  prob: 0.5
  removal_max: 0.2
  removal_intensity: 0.3
  rate_intensity: 0.15
  node_drop_rate: 0.1
  edge_mask_rate: 0.1

model:
  spec_encoder:
    embedding_dim: 512
    n_head: 16
    n_layer: 4
    dim_feedward: 512
    dim_target: 512
    feedward_activation: "selu"
  mol_encoder:
    emb_dim: 128
    n_layers: 4
    dropout_rate: 0.2
  align:
    final_dim: 512
    dropout_rate: 0.2
    tau: 0.07

train:
  pretrain:
    batch_size: 512
    epochs: 50
    lr: 0.000075 # 7.5e-5
    weight_decay: 0.1
    loss:
      temperature: 0.05
      base_temperature: 0.05
    early_stop: 20
  align:
    batch_size: 128
    epochs_stage1: 50
    epochs_stage2: 100
    lr: 0.0001 # 1e-4
    weight_decay: 0.0001 # 1e-4
    patience: 5

eval:
  replications: 10
  top_k: [1, 5, 10, 20]
  loader_batch_size: 1024
  calc_batch_size: 512

paths:
  pretrained_models:
    supcon_tanimoto_aug: "/data1/xp/data/model/transformer-SupConWithTanimotoLoss-Augmentation/model.ckpt"
    supcon_tanimoto: "/data1/xp/code/specEmbedding/SpecEmbedding/model/transformer-SupConWithTanimotoLoss/model.ckpt"
    supcon: "/data1/xp/code/specEmbedding/SpecEmbedding/model/transformer-SupConLoss/model.ckpt"
    tanimoto: "/data1/xp/code/specEmbedding/SpecEmbedding/model/transformer-TanimotoLoss/model.ckpt"
